# Generated by Django 4.0.4 on 2022-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='department',
            field=models.CharField(default='B.Tech', max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='hostel',
            field=models.CharField(default='Siang', max_length=63, null=True),
        ),
    ]
