# Generated by Django 4.0.4 on 2022-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_department_newuser_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
