# Generated by Django 4.0.4 on 2022-06-10 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1023)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Sports', 'Sports'), ('Vehicle', 'Vehicle'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Miscellaneous', 'Miscellaneous')], default='Electronics', max_length=63)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('negotiable', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads_images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.product')),
            ],
        ),
    ]
