# Generated by Django 4.0.4 on 2022-05-31 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_quantity', models.PositiveBigIntegerField()),
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1023)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Sports', 'Sports'), ('Vehicle', 'Vehicle'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Miscellaneous', 'Miscellaneous')], default='Electronics', max_length=63)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
