# Generated by Django 4.0.4 on 2022-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
