# Generated by Django 4.0.4 on 2022-06-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_image_product_id_image_product_product_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
